title: Dans la Jungle
author: pntbr
email: pntbr@scopyleft.fr
description: >
  Daktary est un éco-système d'outils permmettant de faciliter l'édition et la 
  publication de ressources *markdown* hébergées sur *github* ou *gitlab*.

encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

defaults:
  - scope:
      path: ""
    values:
      layout: location

collections:

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings
